// <auto-generated />
using System;
using GGPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GGPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(GGPatlformContext))]
    [Migration("20180818135130_initlCreateMysqDB")]
    partial class initlCreateMysqDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GGPlatoform.Domain.Entity.User.Users", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("IsEnabled");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<int>("LoginCount");

                    b.Property<DateTime>("LookTime");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Sex");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
